Repository Rajpreet0/KitchApp, pull requests merged in 2024-06, with the labels that each got.

#9 refactored class names
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityRecipes.kt
Labels: refactor

#10 added suggestion screen
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Suggestions.kt
  app/src/main/res/drawable/buttonslayout3.xml
  app/src/main/res/layout/suggestions.xml
Labels: enhancement

#12 added functionality to the add button in Fridge activity
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFridge.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/dialog_input.xml
Labels: enhancement

#14 linked profile screen, and add to android manifest
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ProfileActivity.kt
  app/src/main/res/layout/activity_profile.xml
Labels: bug

#15 created networkHelper Class to abstract calls to server
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
Labels: refactor

#16 retrieve user from DB by logging in
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
Labels: enhancement

#17 Feature daria/display recipe
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/RecipeDisplayActivity.kt
  app/src/main/res/drawable/bg_switch.xml
  app/src/main/res/drawable/forkknife.xml
  app/src/main/res/drawable/icon_apple.xml
  app/src/main/res/drawable/icon_book_switch.xml
  app/src/main/res/drawable/minusbtn.xml
  app/src/main/res/drawable/plusbtn.xml
  app/src/main/res/drawable/rounded_border_dirty.xml
  app/src/main/res/drawable/rounded_border_yellow.xml
  app/src/main/res/drawable/switch_background_on.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_recipe_display.xml
Labels: enhancement

#18 changed server addresses to deployed server
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
Labels: enhancement

#19 navigationbar everywhere + add buttons work
  .idea/deploymentTargetSelector.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ProfileActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/RecipeDisplayActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Suggestions.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_groceery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_recipe_display.xml
  app/src/main/res/layout/popup_add_ingredient.xml
  app/src/main/res/layout/suggestions.xml
Labels: refactor

#22 app icon now implemented
  .idea/deploymentTargetSelector.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#25 resized buttons on main screen
  app/src/main/res/layout/activity_main.xml
Labels: refactor

#27 implemented login as starting activity and created button functions
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Activity_login.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Login.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/createaccount.kt
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/activity_login.xml
Labels: enhancement

#29 Feature raj/added login functionality
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Login.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: enhancement

#28 screenrecipepreferences
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/recipepreferences.kt
  app/src/main/res/layout/activity_recipepreferences.xml
Labels: enhancement

#30 uncessary
  app/src/main/res/values/strings.xml
Labels: enhancement

#31 excludeingredientsscreen
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/excludeingredients.kt
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#34 recipe creation screens are now connected with next buttons
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/MainActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Suggestions.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/excludeingredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/recipepreferences.kt
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/suggestions.xml
Labels: enhancement

#36 added register functionality
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/createaccount.kt
Labels: enhancement

#37 fixed validation of different passwords and UI Fix
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/createaccount.kt
  app/src/main/res/layout/activity_createaccount.xml
Labels: bug

#33 Feature emre/recipepreferencesbackrounds
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/recipepreferencesbackrounds.kt
  app/src/main/res/drawable/buttonumrandungneu.xml
  app/src/main/res/layout/activity_recipepreferencesbackrounds.xml
Labels: enhancement

#38 removed duplicate of recipepreferences class
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/recipepreferencesbackrounds.kt
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/activity_recipepreferencesbackrounds.xml
Labels: refactor

#39 adjusted layout(textColor and globe icon) for spinner on profile
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ProfileActivity.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/spinner_items.xml
  app/src/main/res/layout/spinner_items_profile.xml
Labels: enhancement

#40 edited preferance screen: font, strokes, menus
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/Login.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ProfileActivity.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/recipepreferences.kt
  app/src/main/res/drawable/umrandung.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/spinner_items_preferences.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#42 fixed bug in handeling threads for register
  .idea/deploymentTargetSelector.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityLogin.kt
Labels: enhancement

#43 all of the storages now store the data persistently on the device
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityPantry.kt
Labels: enhancement
