Repository Rajpreet0/KitchApp, pull requests merged in 2024-07, with the labels that each got.

#48 fixed route for delivery
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
Labels: refactor

#49 added connection to recipe generation route
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivitySuggestions.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/NetworkHelper.kt
Labels: enhancement

#50 changed all IDs to avoid confusions and stick to a convention
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivitySuggestions.kt
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_recipe_display.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/exclude_layout_row.xml
  app/src/main/res/layout/suggestions.xml
  app/src/main/res/layout/suggestions_layout_row.xml
Labels: enhancement

#54 disabled animation
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivitySuggestions.kt
  app/src/main/res/values/themes.xml
Labels: refactor

#55 Feature daria/suggestions on click
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivitySuggestions.kt
  app/src/main/res/drawable/choosen_recipe_layout.xml
  app/src/main/res/values/colors.xml
Labels: documentation, enhancement

#60 refactored route and response with function calling
  .idea/deploymentTargetSelector.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipePreferences.kt
Labels: refactor

#61 now excluding ingredients is scrollable
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_recipe_display.xml
Labels: enhancement

#62 changed json formatting
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivitySuggestions.kt
Labels: refactor

#63 orginazied files
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/fragments/LoadingDialogFramgent.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/ValidationUtil.kt
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_recipe_display.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/suggestions.xml
Labels: refactor

#65 added validation class
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/ValidationUtil.kt
Labels: enhancement

#68 added Session for authentication
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/SessionManager.kt
Labels: enhancement

#69 added username onto homescreen
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
Labels: enhancement

#70 added time to recipe
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/res/layout/suggestions_layout_row.xml
Labels: enhancement

#71 profile screen functions like edit enabled
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/res/drawable/ic_remove.xml
  app/src/main/res/drawable/ic_save.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/popup_profile.xml
  app/src/main/res/layout/profile_ingredient_layout.xml
Labels: enhancement

#73 shared preferances is updated after edit/save
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/SessionManager.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#76 forgotpassword
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/forgotpassword.kt
  app/src/main/res/layout/activity_forgotpassword.xml
Labels: enhancement

#77 added logout functionality
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement

#79 functionality of deleting user
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement

#78 added reset password screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityResetPassword.kt
  app/src/main/res/layout/activity_reset_password.xml
Labels: enhancement

#82 Only 1 suggestion can be selected now
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/res/layout/ingredient_layout_row.xml
Labels: documentation

#87 recipe display save button is enabledc
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipeDisplay.kt
  app/src/main/res/layout/activity_recipe_display.xml
Labels: documentation

#81 passwordresetsuccessful
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/ActivityPasswordResetSuccess.kt
  app/src/main/res/layout/activity_password_reset_success.xml
Labels: enhancement

#90 Profile screen corrected, language, layout and button functions
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/profile_ingredient_layout.xml
Labels: bug

#91 fixed bug in exclude ingredients
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
Labels: bug

#92 fixed registration
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAcount.kt
Labels: enhancement

#94 preference layout adjusted and add/remove enabled
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/ingredient_layout_preferences.xml
Labels: bug

#95 btn delete disliked adjusted and profile switched from excl to specials
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/strings.xml
Labels: documentation

#97 not instantly delete/logout now
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/res/layout/activity_recipepreferences.xml
Labels: enhancement

#98 Feature/suprise me functionality
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
Labels: enhancement

#99 importing special preferences works now
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement

#100 spinner corrected for all storages
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityPantry.kt
  app/src/main/res/drawable/ic_save_dark.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/ingredient_dialog_add.xml
  app/src/main/res/layout/spinner_items_unit.xml
Labels: bug fix

#101 added suggestions in home
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#102 recipe display corrected
  app/src/main/res/drawable/bg_thumb.xml
  app/src/main/res/drawable/bg_track.xml
  app/src/main/res/drawable/ic_book.xml
  app/src/main/res/layout/activity_recipe_display.xml
  app/src/main/res/values/themes.xml
Labels: documentation

#103 now switch between 10 prompts for suggestions
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
Labels: enhancement

#104 Navi color on change
  app/src/main/res/drawable/ic_heart_selected.xml
  app/src/main/res/drawable/ic_home_select.xml
  app/src/main/res/drawable/ic_list_select.xml
  app/src/main/res/drawable/ic_profile_selected.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
Labels: documentation

#105 changed now correctly
  app/src/main/res/layout/activity_profile.xml
Labels: bug fix

#109 commented
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityForgotPassword.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityPasswordResetSuccess.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/fragments/LoadingDialogFramgent.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/SessionManager.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/ValidationUtil.kt
  app/src/main/res/layout/activity_password_reset_success.xml
Labels: documentation

#111 XML Comments done for Daria
  .idea/deploymentTargetSelector.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/res/drawable/bg_thumb.xml
  app/src/main/res/drawable/checkbox_layout.xml
  app/src/main/res/drawable/checkbox_layout_ingredient.xml
  app/src/main/res/drawable/choosen_recipe_layout.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/activity_main_recipes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_recipe_display.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/ingredient_layout_row.xml
  app/src/main/res/layout/specials_layout_row.xml
  app/src/main/res/layout/spinner_items_preferences.xml
  app/src/main/res/layout/spinner_items_profile.xml
  app/src/main/res/layout/spinner_items_unit.xml
  app/src/main/res/layout/suggestions.xml
  app/src/main/res/layout/suggestions_layout_row.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: documentation

#112 recipe frame corrected
  app/src/main/res/layout/savedrecipe_layout_row.xml
  app/src/main/res/layout/suggestions_layout_row.xml
Labels: documentation

#113 Bugfix ron/refactor saving recipes and logout
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFridge.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityGrocery.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityPantry.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
Labels: bug fix

#114 refactores loading state of suggestions
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
Labels: refactor

#115 info buttons included for preferance activity
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/layout/activity_recipepreferences.xml
Labels: enhancement

#117 comments added
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAcount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityExcludeIngredients.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityFreezer.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipeDisplay.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/res/layout/activity_createaccount.xml
Labels: documentation

#116 comments done for saved Recipe, suggestions, profile
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipes.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivitySuggestions.kt
Labels: documentation

#118 Feature raj/profile screen connection db
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityCreateAccount.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityForgotPassword.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityHome.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityLogin.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityProfile.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityRecipePreferences.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/activities/ActivityResetPassword.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/fragments/LoadingDialogFramgent.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/NetworkHelper.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/SessionManager.kt
  app/src/main/java/de/fra_uas/fb2/mobileApplicationExcercises/kitchapp/helpers/ValidationUtil.kt
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/popup_add_ingredient.xml
Labels: documentation

#120 input
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_forgotpassword.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_password_reset_success.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/suggestions.xml
Labels: enhancement

#122 finishedkonfig
  app/src/main/res/layout/activity_createaccount.xml
  app/src/main/res/layout/activity_excludeingredients.xml
  app/src/main/res/layout/activity_forgotpassword.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_freezer.xml
  app/src/main/res/layout/activity_main_fridge.xml
  app/src/main/res/layout/activity_main_grocery.xml
  app/src/main/res/layout/activity_main_pantry.xml
  app/src/main/res/layout/activity_password_reset_success.xml
  app/src/main/res/layout/activity_recipepreferences.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/suggestions.xml
Labels: enhancement
